export const data = [
    {
        id: '1',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/devto',
        title: 'The Power of Reduce: Optimizing JavaScript Code for Speed and Efficiency',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['webdev', 'javascript', 'react', 'performance'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/d0132092124d7c7bc57433b062a843c6?_a=AQAEuiZ',
        createdAt: '2024-05-19',
        secondsRead: 360,
        upvote: 10,
        comments: 15
    },
    {
        id: '2',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/devto',
        title: 'Weak memoization in Javascript',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['javascript', 'performance'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/12f004840d7081b5f22a2eef9047666f?_a=AQAEuiZ',
        createdAt: '2024-02-19',
        secondsRead: 200,
        upvote: 10,
        comments: 15
    },
    {
        id: '3',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/739e560f0f81492eb54055003476c505',
        title: '🌈 2 Colors Extensions to make Visual Studio Code even better!',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['webdev', 'javascript', 'react', 'performance'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/8d9ca3167f4744c5c647c300bac976e4?_a=AQAEuiZ',
        createdAt: '2024-06-19',
        secondsRead: 360,
        upvote: 10,
        comments: 15
    },
    {
        id: '4',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/739e560f0f81492eb54055003476c505',
        title: 'The Power of Reduce: Optimizing JavaScript Code for Speed and Efficiency',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['webdev', 'javascript', 'react'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/d0132092124d7c7bc57433b062a843c6?_a=AQAEuiZ',
        createdAt: '2024-06-20',
        secondsRead: 500,
        upvote: 10,
        comments: 15
    },
    {
        id: '5',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/devto',
        title: 'The Power of Reduce: Optimizing JavaScript Code for Speed and Efficiency',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['webdev', 'javascript', 'react', 'performance'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/d0132092124d7c7bc57433b062a843c6?_a=AQAEuiZ',
        createdAt: '2024-05-19',
        secondsRead: 360,
        upvote: 10,
        comments: 15
    },
    {
        id: '6',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/devto',
        title: 'Weak memoization in Javascript',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['javascript', 'performance'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/12f004840d7081b5f22a2eef9047666f?_a=AQAEuiZ',
        createdAt: '2024-02-19',
        secondsRead: 200,
        upvote: 10,
        comments: 15
    },
    {
        id: '7',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/739e560f0f81492eb54055003476c505',
        title: '🌈 2 Colors Extensions to make Visual Studio Code even better!',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['webdev', 'javascript', 'react', 'performance'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/8d9ca3167f4744c5c647c300bac976e4?_a=AQAEuiZ',
        createdAt: '2024-06-19',
        secondsRead: 360,
        upvote: 10,
        comments: 15
    },
    {
        id: '8',
        avatar: 'https://res.cloudinary.com/daily-now/image/upload/t_logo,f_auto/v1/logos/739e560f0f81492eb54055003476c505',
        title: 'The Power of Reduce: Optimizing JavaScript Code for Speed and Efficiency',
        description: "  Magna exercitation reprehenderit magna aute tempor cupidatatconsequat elit dolor adipisicing. Mollit dolor eiusmod sunt exincididunt cillum quis. Velit duis sit officia eiusmod Lorem aliqua enim laboris do dolor eiusmod. Et mollit incididunt nisi",
        hashTag: ['webdev', 'javascript', 'react'],
        image: 'https://res.cloudinary.com/daily-now/image/upload/f_auto,q_auto/v1/posts/d0132092124d7c7bc57433b062a843c6?_a=AQAEuiZ',
        createdAt: '2024-06-20',
        secondsRead: 500,
        upvote: 10,
        comments: 15
    },
]